@startuml
'https://plantuml.com/class-diagram

object Config {
    - properties: Properties
    + boardDim: Int
    + numPieces: Int
    + minimalPlaysToJoin: Int
    + checkersPoints: Int
    --
    - loadProperties(): void
}

class Properties

Config --> Properties : uses

@enduml
